url: https://tiagofeitor.github.io/es-2019-2020-P13.github.io/
baseurl: /es-2019-2020-P13.github.io/

# Site settings
title: BusFind Porto
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: André Santos
  pic: 1
  position:
  

- name: Marlene Bastos
  pic: 2
  position:
 

- name: Diogo Alexandre Duarte
  pic: 3
  position:
 
- name: Alexandre Machado
  pic: 4
  position:
  
- name: Tiago Feitor
  pic: 5
  position:
 
  url: #
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line:
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
